### ISSUE TITLE
[STU-175] Attempt to read property "name" on null 

### ISSUE THREAD

**Issue by janhenckens** [studioespresso/craft-easyaddressfield#39]
Hello, I'm encountering a similar issue while using v.4.0.10 on Craft 4.11.5.

`yii\base\ErrorException: Attempt to read property "name" on null in /var/www/html/vendor/studioespresso/craft-easyaddressfield/src/services/FieldService.php:48
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Attempt to read...', '/var/www/html/v...', 48)
#1 /var/www/html/vendor/studioespresso/craft-easyaddressfield/src/services/FieldService.php(48): craft\web\ErrorHandler->handleError(2, 'Attempt to read...', '/var/www/html/v...', 48)
#2 /var/www/html/vendor/studioespresso/craft-easyaddressfield/src/fields/EasyAddressFieldField.php(201): studioespresso\easyaddressfield\services\FieldService->saveField(Object(studioespresso\easyaddressfield\fields\EasyAddressFieldField), Object(craft\elements\Entry))
#3 /var/www/html/vendor/craftcms/cms/src/base/Element.php(5164): studioespresso\easyaddressfield\fields\EasyAddressFieldField->afterElementSave(Object(craft\elements\Entry), false)
#4 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(2023): craft\base\Element->afterSave(false)
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(3461): craft\elements\Entry->afterSave(false)
#6 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1114): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, true, true, Array, false, false)
#7 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(382): craft\services\Elements->saveElement(Object(craft\elements\Entry), false)
#8 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(318): craft\services\Drafts->removeDraftData(Object(craft\elements\Entry))
#9 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(1510): craft\services\Drafts->applyDraft(Object(craft\elements\Entry))
#10 [internal function]: craft\controllers\ElementsController->actionApplyDraft()
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('apply-draft', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(340): yii\base\Module->runAction('elements/apply-...', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(639): craft\web\Application->runAction('elements/apply-...', Array)
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(302): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/html/web/index.php(12): yii\base\Application->run()
#19 {main}`

_Originally posted by @wolf-ms in https://github.com/studioespresso/craft-easyaddressfield/issues/37#issuecomment-2322191002_
            

<sub>[STU-175](https://linear.app/studio-espresso/issue/STU-175/attempt-to-read-property-name-on-null)</sub>

**Comment by wolf-ms** [comment]
@janhenckens Just checking in to see if there's been an update on this or whether I need to provide more info. Thanks!

**Comment by janhenckens** [comment]
Hey @wolf-ms, I haven't gotten the chance to look into it further, will try to get back to you early next week!

**Comment by janhenckens** [comment]
@wolf-ms should be fixed in 4.0.11 (and 5.0.2 for Craft 5) - can you give that a try? Thanks!

**Comment by wolf-ms** [comment]
Thanks for looking into this @janhenckens ! The 'Attempt to read property "name" on null' no longer appears when I save an entry, but the longitude/latitude coordinates are not populating after save. The 'Pick an address on the map" option isn't working either if it's a new entry and the coordinates haven't been generated yet. It just shows a blank modal with Cancel and Done buttons (the Cancel button doesn't work).

**Comment by wolf-ms** [comment]
@janhenckens Attaching a screenshot with the an address
![Address-field](https://github.com/user-attachments/assets/9cef1cad-b137-4916-91db-43c8f4722e7d)

**Comment by janhenckens** [comment]
hey @wolf-ms, the plugin has had a sizable update:
- we're catching Nominatim issues without crashing
- you can now also configure Google's Geocoding API, which is more stable and less rate limited
I'll close this issue for now, should you run into any other issues with the plugin, feel free to get in touch!
